//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLICATION_REQUEST
    {
        public APPLICATION_REQUEST()
        {
            this.APPLICATION_REQUEST_USERS = new HashSet<APPLICATION_REQUEST_USERS>();
        }
    
        public decimal REQUESTID { get; set; }
        public string BUYERAGENTID { get; set; }
        public string BUYERPCC { get; set; }
        public string APPLICATIONID { get; set; }
        public string APPLICATIONVERSION { get; set; }
        public Nullable<System.DateTime> REQUESTDATE { get; set; }
        public Nullable<System.DateTime> APPROVEDDATE { get; set; }
        public Nullable<System.DateTime> SALEDATE { get; set; }
        public Nullable<System.DateTime> LASTUPDATE { get; set; }
        public Nullable<decimal> PURCHASEPRICE { get; set; }
        public string REQUESTSTATUS { get; set; }
        public string BUYERAGENCYNAME { get; set; }
        public Nullable<decimal> ENTIREAGENCY { get; set; }
    
        public virtual ICollection<APPLICATION_REQUEST_USERS> APPLICATION_REQUEST_USERS { get; set; }
    }
}
