//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCC_Message
    {
        public MCC_Message()
        {
            this.MCC_MessageRecipient = new HashSet<MCC_MessageRecipient>();
            this.MCC_MessageInDirectory = new HashSet<MCC_MessageInDirectory>();
        }
    
        public decimal Id { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public System.DateTime SentDate { get; set; }
        public Nullable<decimal> SenderId { get; set; }
        public Nullable<decimal> ConversationId { get; set; }
    
        public virtual ICollection<MCC_MessageRecipient> MCC_MessageRecipient { get; set; }
        public virtual MCC_User MCC_User { get; set; }
        public virtual ICollection<MCC_MessageInDirectory> MCC_MessageInDirectory { get; set; }
    }
}
