//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCC_User
    {
        public MCC_User()
        {
            this.MCC_Directory = new HashSet<MCC_Directory>();
            this.MCC_Message = new HashSet<MCC_Message>();
            this.MCC_MessageRecipient = new HashSet<MCC_MessageRecipient>();
        }
    
        public decimal Id { get; set; }
        public string Name { get; set; }
        public string SabreID { get; set; }
        public string Pcc { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> CompanyId { get; set; }
    
        public virtual MCC_Company MCC_Company { get; set; }
        public virtual ICollection<MCC_Directory> MCC_Directory { get; set; }
        public virtual ICollection<MCC_Message> MCC_Message { get; set; }
        public virtual ICollection<MCC_MessageRecipient> MCC_MessageRecipient { get; set; }
    }
}
