//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFConsole
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<APPLICATION_REQUEST> APPLICATION_REQUEST { get; set; }
        public DbSet<APPLICATION_REQUEST_USERS> APPLICATION_REQUEST_USERS { get; set; }
        public DbSet<MCC_Company> MCC_Company { get; set; }
        public DbSet<MCC_Directory> MCC_Directory { get; set; }
        public DbSet<MCC_Message> MCC_Message { get; set; }
        public DbSet<MCC_MessageInDirectory> MCC_MessageInDirectory { get; set; }
        public DbSet<MCC_MessageRecipient> MCC_MessageRecipient { get; set; }
        public DbSet<MCC_User> MCC_User { get; set; }
        public DbSet<SVS_CONVERSATION> SVS_CONVERSATION { get; set; }
    }
}
