//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLICATION_REQUEST_USERS
    {
        public decimal REQUESTID { get; set; }
        public string AGENTID { get; set; }
        public string PCC { get; set; }
        public Nullable<System.DateTime> DATEADDED { get; set; }
    
        public virtual APPLICATION_REQUEST APPLICATION_REQUEST { get; set; }
    }
}
